services:
    app:
        container_name: lion-packages-app
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "4322:4322"
        volumes:
            - ./:/var/www/html
        networks:
            - lion
networks:
    lion:
        driver: bridge